export const FEATURES = {
  A2: {
    code: 'A2',
    title: 'Đơn vị của tôi',
    description:
      'Chọn một đơn vị để lọc toàn bộ dashboard, cảnh báo và nhật ký. Mặc định đang xem gộp tất cả đơn vị được phân công.',
  },
  A3: {
    code: 'A3',
    title: 'Hồ sơ cá nhân',
    description: 'Cập nhật thông tin liên hệ. Đổi mật khẩu cần mật khẩu hiện tại.',
  },
  B1: {
    code: 'B1',
    title: 'Quản lý tài khoản khách hàng',
    description:
      'Tài khoản App nông dân: tạo, khóa hoặc đặt lại mật khẩu. Không lẫn với Admin / KTV / Quản lý. Khóa/xóa ghi nhật ký hoạt động.',
    role: 'Admin',
    scope: 'Toàn hệ thống — nông dân',
    ux: 'Page + Modal',
    source: 'Không — tài khoản App',
  },
  B1_STAFF: {
    code: 'B1_STAFF',
    title: 'Quản lý tài khoản',
    description:
      'Tài khoản website quản trị: Admin, Quản lý doanh nghiệp/HTX, Kỹ thuật viên. Khóa/xóa ghi nhật ký hoạt động.',
    role: 'Admin',
    scope: 'Toàn hệ thống — nhân sự',
    ux: 'Page + Modal',
    source: 'Không — tài khoản web',
  },
  B0: {
    code: 'B0',
    title: 'Dashboard hệ thống',
    description: 'Biểu đồ dữ liệu UAV và thiết bị IoT theo vùng, cùng chỉ số cảnh báo bệnh đang mở.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Chỉ xem',
    source: 'UAV + IoT + cảnh báo ảnh',
  },
  B9: {
    code: 'B9',
    title: 'Phương án giải quyết bệnh cây lúa',
    description: 'Danh mục phương án theo 9 lớp bệnh. Import Excel để bổ sung phương pháp điều trị.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Import Excel + xem catalog',
    source: 'Catalog bệnh',
  },
  B10: {
    code: 'B10',
    title: 'Cảnh báo vận hành (Admin)',
    description: 'Cảnh báo nguy cơ IoT, sự cố trạm và thông báo hệ thống — không gồm báo cáo ảnh nông dân.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Page master-detail',
    source: 'IoT + hệ thống',
  },
  B2: {
    code: 'B2',
    title: 'Quản lý đơn vị',
    description: 'Duyệt đăng ký, tạo thủ công, khóa/mở đơn vị HTX/doanh nghiệp.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Page + Inline + Modal',
    source: 'Không — danh mục',
  },
  B3: {
    code: 'B3',
    title: 'Quản lý thiết bị IoT',
    description: 'Lưới khung trạm: thêm/sửa/xóa, gán thửa, xem cảm biến và quản lý sự cố.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Khung + Modal + trang chi tiết',
    source: 'Cảm biến IoT',
  },
  B4: {
    code: 'B4',
    title: 'Cấu hình ngưỡng cảnh báo & mô hình AI',
    description: 'Chỉnh ngưỡng môi trường và tham số mô hình. Áp dụng sau bước staging.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Dedicated page',
    source: 'Cấu hình',
  },
  B5: {
    code: 'B5',
    title: 'Giám sát tình trạng hệ thống',
    description: 'IoT online/offline, độ trễ API, tỷ lệ lỗi, sparkline theo giờ và log sự cố gần đây.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Chỉ xem',
    source: 'IoT + hệ thống',
  },
  B6: {
    code: 'B6',
    title: 'Dữ liệu huấn luyện AI',
    description: 'Chỉ ảnh/cảnh báo đã chuyên gia xác nhận mới vào tập train.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Dedicated page',
    source: 'Ảnh App / UAV + phản hồi D4',
  },
  B7: {
    code: 'B7',
    title: 'Nhật ký hoạt động hệ thống',
    description: 'Audit log các thao tác khóa, gán, cấu hình. Lọc theo hành động.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Chỉ xem',
    source: 'Hệ thống',
  },
  B8: {
    code: 'B8',
    title: 'Phân công kỹ thuật viên cho đơn vị',
    description: 'Gán KTV cho đơn vị. KTV không tự đăng ký đơn vị.',
    role: 'Admin',
    scope: 'Toàn hệ thống',
    ux: 'Modal gán + Inline gỡ',
    source: 'Không — phân quyền',
  },
  C1: {
    code: 'C1',
    title: 'Dashboard đơn vị',
    description: 'Diện tích, thửa cảnh báo, KTV, tỷ lệ cảnh báo đúng, xu hướng và xếp hạng vùng.',
    role: 'Quản lý doanh nghiệp/HTX',
    scope: 'Đơn vị của mình',
    ux: 'Chỉ xem',
    source: 'IoT + ảnh + nhật ký',
  },
  C2: {
    code: 'C2',
    title: 'Danh sách kỹ thuật viên',
    description: 'Xem KTV phụ trách và phân công vùng. Không tự thêm/xóa — liên hệ Admin.',
    role: 'Quản lý doanh nghiệp/HTX',
    scope: 'Đơn vị của mình',
    ux: 'Danh sách + Modal',
    source: 'Không — nhân sự',
  },
  C3: {
    code: 'C3',
    title: 'Quản lý vùng trồng / thửa ruộng',
    description: 'Vẽ ranh giới trên bản đồ, liên kết hộ nông dân. Sửa tên, diện tích, giống tại chỗ.',
    role: 'Quản lý doanh nghiệp/HTX',
    scope: 'Đơn vị của mình',
    ux: 'Page + Inline',
    source: 'Bản đồ + danh mục',
  },
  C4: {
    code: 'C4',
    title: 'Báo cáo tổng hợp mùa vụ',
    description: 'Tổng hợp diện tích, cảnh báo, nhật ký theo mùa. Lọc tại chỗ.',
    role: 'Quản lý doanh nghiệp/HTX',
    scope: 'Đơn vị của mình',
    ux: 'Chỉ xem, lọc Inline',
    source: 'Nhật ký + cảnh báo',
  },
  C5: {
    code: 'C5',
    title: 'Xuất báo cáo truy xuất nguồn gốc',
    description: 'Chọn thửa và mùa vụ, xuất file CSV/TXT minh họa.',
    role: 'Quản lý doanh nghiệp/HTX',
    scope: 'Đơn vị của mình',
    ux: 'Dedicated page',
    source: 'Nhật ký + mùa vụ',
  },
  C6: {
    code: 'C6',
    title: 'Quản lý hộ nông dân',
    description: 'Thêm hộ, sửa liên hệ tại chỗ, cấp tài khoản App (mock).',
    role: 'Quản lý doanh nghiệp/HTX',
    scope: 'Đơn vị của mình',
    ux: 'Page + Modal + Inline',
    source: 'Không — danh mục',
  },
  D1: {
    code: 'D1',
    title: 'Dashboard vùng trồng được phân công',
    description: 'Thửa nguy cơ cao được đưa lên đầu, bất kể thuộc đơn vị nào.',
  },
  D2: {
    code: 'D2',
    title: 'Bản đồ vùng trồng',
    description:
      'Mỗi ô là một thửa (không xếp theo tỉnh). Ảnh UAV hoặc ảnh upload, tên nông dân, trạm IoT. Click ô để xem chi tiết.',
    role: 'KTV / Quản lý HTX',
    scope: 'Đơn vị đang xem',
    ux: 'Lưới ô + trang chi tiết',
    source: 'IoT + ảnh UAV / upload',
  },
  D3: {
    code: 'D3',
    title: 'Danh sách cảnh báo bệnh hại',
    description: 'Phân biệt dự báo nguy cơ và kết quả nhận diện từ ảnh.',
  },
  D3_DISEASE: {
    code: 'D3',
    title: 'Cảnh báo bệnh',
    description: 'Báo cáo bệnh khi nông dân chụp ảnh và gửi lên hệ thống (nhận diện từ ảnh App).',
  },
  D5: {
    code: 'D5',
    title: 'Chi tiết cảm biến IoT',
    description: 'Chuỗi thời gian 5 chỉ số theo trạm, so sánh với ngưỡng. Không cache realtime.',
    role: 'Kỹ thuật viên',
    scope: 'Đơn vị được phân công',
    ux: 'Chỉ xem, lọc Inline',
    source: 'Cảm biến IoT',
  },
  D6: {
    code: 'D6',
    title: 'Ảnh nông dân & kết quả nhận diện',
    description: 'Đối chiếu nhãn App với quét lại YOLO trên web, xem giải pháp theo 9 loại bệnh, rồi xác nhận đã xem xét.',
    role: 'Kỹ thuật viên',
    scope: 'Đơn vị được phân công',
    ux: 'Chỉ xem + Modal',
    source: 'Ảnh từ App nông dân',
  },
  D7: {
    code: 'D7',
    title: 'Dữ liệu UAV theo đợt khảo sát',
    description: 'Xử lý bất đồng bộ (trạng thái giả lập). Không tải ảnh lớn trên request.',
    role: 'Kỹ thuật viên',
    scope: 'Đơn vị được phân công',
    ux: 'Dedicated page',
    source: 'Ảnh UAV',
  },
  D8: {
    code: 'D8',
    title: 'Nhật ký đồng ruộng',
    description: 'Gieo sạ, phân, thuốc, tưới, thu hoạch. Tạo bằng hộp thoại.',
    role: 'Kỹ thuật viên',
    scope: 'Đơn vị được phân công',
    ux: 'Modal',
    source: 'Nhật ký',
  },
  D9: {
    code: 'D9',
    title: 'Trạm cảm biến tại thửa',
    description: 'Thêm/sửa/gỡ trạm từ trang chi tiết thửa (D2). Trang này quản lý sự cố, cảm biến, báo cáo.',
    role: 'Kỹ thuật viên',
    scope: 'Đơn vị được phân công',
    ux: 'Từ thửa + trang chi tiết trạm',
    source: 'Cảm biến IoT',
  },
  D10: {
    code: 'D10',
    title: 'Lịch kiểm tra thực địa',
    description: 'Tạo lịch, đánh dấu hoàn thành. Có thể liên kết cảnh báo D4.',
    role: 'Kỹ thuật viên',
    scope: 'Đơn vị được phân công',
    ux: 'Modal tạo + Inline hoàn thành',
    source: 'Không — lịch',
  },
  E1: {
    code: 'E1',
    title: 'Trung tâm thông báo',
    description: 'Danh sách gộp theo phạm vi đang xem. Đánh dấu đã đọc tại chỗ.',
  },
  E2: {
    code: 'E2',
    title: 'Tìm kiếm toàn hệ thống',
    description: 'Tìm thửa, cảnh báo, hộ, trạm theo quyền. Debounce ô tìm, không gọi mỗi ký tự.',
    role: 'Cả 3 (theo quyền)',
    scope: 'Theo vai trò / đơn vị',
    ux: 'Inline',
    source: 'Chỉ mục mock',
  },
  E3: {
    code: 'E3',
    title: 'Cài đặt chung',
    description: 'Ngôn ngữ, thông báo, múi giờ. Một số mục chỉ Admin.',
    role: 'Cả 3',
    scope: 'Tài khoản; hệ thống (Admin)',
    ux: 'Inline',
    source: 'Không',
  },
  B11: {
    code: 'B11',
    title: 'Bản tin nông dân',
    description:
      'Soạn và xuất bản bài viết trên App. KTV soạn phải gửi duyệt; Admin duyệt hoặc xuất bản trực tiếp.',
    role: 'Admin / KTV',
    scope: 'Toàn hệ thống (App nông dân)',
    ux: 'Page list + Dedicated editor',
    source: 'CMS nội bộ qua Flask',
  },
  B12: {
    code: 'B12',
    title: 'Hỏi đáp bản tin',
    description: 'Tiếp nhận thắc mắc nông dân theo bài viết, trả lời và tùy chọn công khai FAQ (khác D4).',
    role: 'Admin / KTV',
    scope: 'Toàn hệ thống',
    ux: 'Master-detail + Modal trả lời',
    source: 'Câu hỏi từ App',
  },
}

export const PLACEHOLDER_BANNER = 'Khung trang — mock API ở wave sau.'

export const ARTICLE_CATEGORY_LABELS = {
  ky_thuat: 'Kỹ thuật',
  canh_bao: 'Cảnh báo',
  he_thong: 'Hệ thống',
}

export const ARTICLE_STATUS_LABELS = {
  draft: 'Nháp',
  pending_review: 'Chờ duyệt',
  published: 'Đã xuất bản',
  archived: 'Đã lưu trữ',
}

export const QUESTION_STATUS_LABELS = {
  open: 'Chưa trả lời',
  answered: 'Đã trả lời',
  hidden: 'Đã ẩn',
}
